TARIFF: OCTOPUS_INTELLI_FLUX
rates:
  import_peak_rate: 0.2997
  export_peak_rate: 0.2997
  import_offpeak_rate: 0.2248
  export_offpeak_rate: 0.2248
  import_standard_rate: 0.201
  export_standard_rate: 0.101
baseline_rate: 0.2467
