TARIFF: OCTOPUS_FLUX
rates:
  import_offpeak_rate: 0.1479
  import_standard_rate: 0.2465
  import_peak_rate: 0.3451
  export_offpeak_rate: 0.0537
  export_standard_rate: 0.1515
  export_peak_rate: 0.251
baseline_rate: 0.2466
