name: default
variables:
  - name: OCTOPUS_API_KEY
    value: "{{process.env.OCTOPUS_API_KEY}}"
  - name: EXPORT_MPAN
    value: "{{process.env.EXPORT_MPAN}}"
  - name: METER_SERIAL
    value: "{{process.env.METER_SERIAL}}"
  - name: IMPORT_MPAN
    value: "{{process.env.IMPORT_MPAN}}"
  - name: OCTOPUS_ACCOUNT_NO
    value: "{{process.env.OCTOPUS_ACCOUNT_NO}}"
  - name: GIVENERGY_API_KEY
    value: "{{process.env.GIVENERGY_API_KEY}}"
  - name: GIVENERGY_DEVICE_ID
    value: "{{process.env.GIVENERGY_DEVICE_ID}}"
